name: web_hover_menu
description: A new Flutter web project that will provide different type of animation with different alignment.
version: 0.0.2
repository : https://github.com/Mindinventory/web_animated_menu

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
