name: web_hover_menu
description: A new Flutter web project that will provide different type of animation with different alignment.
version: 0.0.1
repository : https://git.mindinventory.com/github/web_animated_menu_flutter/-/tree/development

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
